controller_manager:
  ros__parameters:
    use_sim_time: True
    update_rate: 1000  # Hz

    joint_states_controller:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_group_effort_controller:
      type: effort_controllers/JointGroupEffortController

      # joint_trajectory_controller/JointTrajectoryController
      # effort_controllers/JointGroupEffortController
      # position_controllers/JointGroupPositionController 

joint_group_effort_controller:
  ros__parameters:
    use_sim_time: True
    joints:
        - lf_hip_joint
        - lf_upper_leg_joint
        - lf_lower_leg_joint
        - rf_hip_joint
        - rf_upper_leg_joint
        - rf_lower_leg_joint
        - lh_hip_joint
        - lh_upper_leg_joint
        - lh_lower_leg_joint
        - rh_hip_joint
        - rh_upper_leg_joint
        - rh_lower_leg_joint 

    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity

    gains:
      FL_hip_joint   : {p: 180.0, d: 0.9, i: 20.0}
      FL_thigh_joint : {p: 180.0, d: 0.9, i: 20.0}
      FL_calf_joint  : {p: 180.0, d: 0.9, i: 20.0}
      FR_hip_joint   : {p: 180.0, d: 0.9, i: 20.0}
      FR_thigh_joint : {p: 180.0, d: 0.9, i: 20.0}
      FR_calf_joint  : {p: 180.0, d: 0.9, i: 20.0}
      RL_hip_joint   : {p: 180.0, d: 0.9, i: 20.0}
      RL_thigh_joint : {p: 180.0, d: 0.9, i: 20.0}
      RL_calf_joint  : {p: 180.0, d: 0.9, i: 20.0}
      RR_hip_joint   : {p: 180.0, d: 0.9, i: 20.0}
      RR_thigh_joint : {p: 180.0, d: 0.9, i: 20.0}
      RR_calf_joint  : {p: 180.0, d: 0.9, i: 20.0}

